/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as MyTicketsRouteImport } from './routes/my-tickets'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HostOnboardingRouteImport } from './routes/host.onboarding'
import { Route as HostDashboardRouteImport } from './routes/host.dashboard'
import { Route as EventsIdRouteImport } from './routes/events.$id'
import { Route as HostEventsNewRouteImport } from './routes/host.events.new'
import { Route as HostEventsIdEditRouteImport } from './routes/host.events.$id.edit'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const MyTicketsRoute = MyTicketsRouteImport.update({
  id: '/my-tickets',
  path: '/my-tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HostOnboardingRoute = HostOnboardingRouteImport.update({
  id: '/host/onboarding',
  path: '/host/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const HostDashboardRoute = HostDashboardRouteImport.update({
  id: '/host/dashboard',
  path: '/host/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIdRoute = EventsIdRouteImport.update({
  id: '/events/$id',
  path: '/events/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const HostEventsNewRoute = HostEventsNewRouteImport.update({
  id: '/host/events/new',
  path: '/host/events/new',
  getParentRoute: () => rootRouteImport,
} as any)
const HostEventsIdEditRoute = HostEventsIdEditRouteImport.update({
  id: '/host/events/$id/edit',
  path: '/host/events/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/my-tickets': typeof MyTicketsRoute
  '/signup': typeof SignupRoute
  '/events/$id': typeof EventsIdRoute
  '/host/dashboard': typeof HostDashboardRoute
  '/host/onboarding': typeof HostOnboardingRoute
  '/host/events/new': typeof HostEventsNewRoute
  '/host/events/$id/edit': typeof HostEventsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/my-tickets': typeof MyTicketsRoute
  '/signup': typeof SignupRoute
  '/events/$id': typeof EventsIdRoute
  '/host/dashboard': typeof HostDashboardRoute
  '/host/onboarding': typeof HostOnboardingRoute
  '/host/events/new': typeof HostEventsNewRoute
  '/host/events/$id/edit': typeof HostEventsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/my-tickets': typeof MyTicketsRoute
  '/signup': typeof SignupRoute
  '/events/$id': typeof EventsIdRoute
  '/host/dashboard': typeof HostDashboardRoute
  '/host/onboarding': typeof HostOnboardingRoute
  '/host/events/new': typeof HostEventsNewRoute
  '/host/events/$id/edit': typeof HostEventsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/my-tickets'
    | '/signup'
    | '/events/$id'
    | '/host/dashboard'
    | '/host/onboarding'
    | '/host/events/new'
    | '/host/events/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/my-tickets'
    | '/signup'
    | '/events/$id'
    | '/host/dashboard'
    | '/host/onboarding'
    | '/host/events/new'
    | '/host/events/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/my-tickets'
    | '/signup'
    | '/events/$id'
    | '/host/dashboard'
    | '/host/onboarding'
    | '/host/events/new'
    | '/host/events/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  MyTicketsRoute: typeof MyTicketsRoute
  SignupRoute: typeof SignupRoute
  EventsIdRoute: typeof EventsIdRoute
  HostDashboardRoute: typeof HostDashboardRoute
  HostOnboardingRoute: typeof HostOnboardingRoute
  HostEventsNewRoute: typeof HostEventsNewRoute
  HostEventsIdEditRoute: typeof HostEventsIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-tickets': {
      id: '/my-tickets'
      path: '/my-tickets'
      fullPath: '/my-tickets'
      preLoaderRoute: typeof MyTicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/onboarding': {
      id: '/host/onboarding'
      path: '/host/onboarding'
      fullPath: '/host/onboarding'
      preLoaderRoute: typeof HostOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/dashboard': {
      id: '/host/dashboard'
      path: '/host/dashboard'
      fullPath: '/host/dashboard'
      preLoaderRoute: typeof HostDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$id': {
      id: '/events/$id'
      path: '/events/$id'
      fullPath: '/events/$id'
      preLoaderRoute: typeof EventsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/events/new': {
      id: '/host/events/new'
      path: '/host/events/new'
      fullPath: '/host/events/new'
      preLoaderRoute: typeof HostEventsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/events/$id/edit': {
      id: '/host/events/$id/edit'
      path: '/host/events/$id/edit'
      fullPath: '/host/events/$id/edit'
      preLoaderRoute: typeof HostEventsIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  MyTicketsRoute: MyTicketsRoute,
  SignupRoute: SignupRoute,
  EventsIdRoute: EventsIdRoute,
  HostDashboardRoute: HostDashboardRoute,
  HostOnboardingRoute: HostOnboardingRoute,
  HostEventsNewRoute: HostEventsNewRoute,
  HostEventsIdEditRoute: HostEventsIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
