/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as MyTicketsRouteImport } from './routes/my-tickets'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CheckerRouteImport } from './routes/checker'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HostOnboardingRouteImport } from './routes/host.onboarding'
import { Route as HostDashboardRouteImport } from './routes/host.dashboard'
import { Route as EventsIdRouteImport } from './routes/events.$id'
import { Route as HostEventsNewRouteImport } from './routes/host.events.new'
import { Route as CheckerAcceptTokenRouteImport } from './routes/checker.accept.$token'
import { Route as HostEventsIdModerationRouteImport } from './routes/host.events.$id.moderation'
import { Route as HostEventsIdEditRouteImport } from './routes/host.events.$id.edit'
import { Route as HostEventsIdCheckInRouteImport } from './routes/host.events.$id.check-in'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const MyTicketsRoute = MyTicketsRouteImport.update({
  id: '/my-tickets',
  path: '/my-tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckerRoute = CheckerRouteImport.update({
  id: '/checker',
  path: '/checker',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HostOnboardingRoute = HostOnboardingRouteImport.update({
  id: '/host/onboarding',
  path: '/host/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const HostDashboardRoute = HostDashboardRouteImport.update({
  id: '/host/dashboard',
  path: '/host/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIdRoute = EventsIdRouteImport.update({
  id: '/events/$id',
  path: '/events/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const HostEventsNewRoute = HostEventsNewRouteImport.update({
  id: '/host/events/new',
  path: '/host/events/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckerAcceptTokenRoute = CheckerAcceptTokenRouteImport.update({
  id: '/accept/$token',
  path: '/accept/$token',
  getParentRoute: () => CheckerRoute,
} as any)
const HostEventsIdModerationRoute = HostEventsIdModerationRouteImport.update({
  id: '/host/events/$id/moderation',
  path: '/host/events/$id/moderation',
  getParentRoute: () => rootRouteImport,
} as any)
const HostEventsIdEditRoute = HostEventsIdEditRouteImport.update({
  id: '/host/events/$id/edit',
  path: '/host/events/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const HostEventsIdCheckInRoute = HostEventsIdCheckInRouteImport.update({
  id: '/host/events/$id/check-in',
  path: '/host/events/$id/check-in',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checker': typeof CheckerRouteWithChildren
  '/login': typeof LoginRoute
  '/my-tickets': typeof MyTicketsRoute
  '/signup': typeof SignupRoute
  '/events/$id': typeof EventsIdRoute
  '/host/dashboard': typeof HostDashboardRoute
  '/host/onboarding': typeof HostOnboardingRoute
  '/checker/accept/$token': typeof CheckerAcceptTokenRoute
  '/host/events/new': typeof HostEventsNewRoute
  '/host/events/$id/check-in': typeof HostEventsIdCheckInRoute
  '/host/events/$id/edit': typeof HostEventsIdEditRoute
  '/host/events/$id/moderation': typeof HostEventsIdModerationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checker': typeof CheckerRouteWithChildren
  '/login': typeof LoginRoute
  '/my-tickets': typeof MyTicketsRoute
  '/signup': typeof SignupRoute
  '/events/$id': typeof EventsIdRoute
  '/host/dashboard': typeof HostDashboardRoute
  '/host/onboarding': typeof HostOnboardingRoute
  '/checker/accept/$token': typeof CheckerAcceptTokenRoute
  '/host/events/new': typeof HostEventsNewRoute
  '/host/events/$id/check-in': typeof HostEventsIdCheckInRoute
  '/host/events/$id/edit': typeof HostEventsIdEditRoute
  '/host/events/$id/moderation': typeof HostEventsIdModerationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checker': typeof CheckerRouteWithChildren
  '/login': typeof LoginRoute
  '/my-tickets': typeof MyTicketsRoute
  '/signup': typeof SignupRoute
  '/events/$id': typeof EventsIdRoute
  '/host/dashboard': typeof HostDashboardRoute
  '/host/onboarding': typeof HostOnboardingRoute
  '/checker/accept/$token': typeof CheckerAcceptTokenRoute
  '/host/events/new': typeof HostEventsNewRoute
  '/host/events/$id/check-in': typeof HostEventsIdCheckInRoute
  '/host/events/$id/edit': typeof HostEventsIdEditRoute
  '/host/events/$id/moderation': typeof HostEventsIdModerationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checker'
    | '/login'
    | '/my-tickets'
    | '/signup'
    | '/events/$id'
    | '/host/dashboard'
    | '/host/onboarding'
    | '/checker/accept/$token'
    | '/host/events/new'
    | '/host/events/$id/check-in'
    | '/host/events/$id/edit'
    | '/host/events/$id/moderation'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checker'
    | '/login'
    | '/my-tickets'
    | '/signup'
    | '/events/$id'
    | '/host/dashboard'
    | '/host/onboarding'
    | '/checker/accept/$token'
    | '/host/events/new'
    | '/host/events/$id/check-in'
    | '/host/events/$id/edit'
    | '/host/events/$id/moderation'
  id:
    | '__root__'
    | '/'
    | '/checker'
    | '/login'
    | '/my-tickets'
    | '/signup'
    | '/events/$id'
    | '/host/dashboard'
    | '/host/onboarding'
    | '/checker/accept/$token'
    | '/host/events/new'
    | '/host/events/$id/check-in'
    | '/host/events/$id/edit'
    | '/host/events/$id/moderation'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckerRoute: typeof CheckerRouteWithChildren
  LoginRoute: typeof LoginRoute
  MyTicketsRoute: typeof MyTicketsRoute
  SignupRoute: typeof SignupRoute
  EventsIdRoute: typeof EventsIdRoute
  HostDashboardRoute: typeof HostDashboardRoute
  HostOnboardingRoute: typeof HostOnboardingRoute
  HostEventsNewRoute: typeof HostEventsNewRoute
  HostEventsIdCheckInRoute: typeof HostEventsIdCheckInRoute
  HostEventsIdEditRoute: typeof HostEventsIdEditRoute
  HostEventsIdModerationRoute: typeof HostEventsIdModerationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-tickets': {
      id: '/my-tickets'
      path: '/my-tickets'
      fullPath: '/my-tickets'
      preLoaderRoute: typeof MyTicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checker': {
      id: '/checker'
      path: '/checker'
      fullPath: '/checker'
      preLoaderRoute: typeof CheckerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/onboarding': {
      id: '/host/onboarding'
      path: '/host/onboarding'
      fullPath: '/host/onboarding'
      preLoaderRoute: typeof HostOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/dashboard': {
      id: '/host/dashboard'
      path: '/host/dashboard'
      fullPath: '/host/dashboard'
      preLoaderRoute: typeof HostDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$id': {
      id: '/events/$id'
      path: '/events/$id'
      fullPath: '/events/$id'
      preLoaderRoute: typeof EventsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/events/new': {
      id: '/host/events/new'
      path: '/host/events/new'
      fullPath: '/host/events/new'
      preLoaderRoute: typeof HostEventsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checker/accept/$token': {
      id: '/checker/accept/$token'
      path: '/accept/$token'
      fullPath: '/checker/accept/$token'
      preLoaderRoute: typeof CheckerAcceptTokenRouteImport
      parentRoute: typeof CheckerRoute
    }
    '/host/events/$id/moderation': {
      id: '/host/events/$id/moderation'
      path: '/host/events/$id/moderation'
      fullPath: '/host/events/$id/moderation'
      preLoaderRoute: typeof HostEventsIdModerationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/events/$id/edit': {
      id: '/host/events/$id/edit'
      path: '/host/events/$id/edit'
      fullPath: '/host/events/$id/edit'
      preLoaderRoute: typeof HostEventsIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/events/$id/check-in': {
      id: '/host/events/$id/check-in'
      path: '/host/events/$id/check-in'
      fullPath: '/host/events/$id/check-in'
      preLoaderRoute: typeof HostEventsIdCheckInRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CheckerRouteChildren {
  CheckerAcceptTokenRoute: typeof CheckerAcceptTokenRoute
}

const CheckerRouteChildren: CheckerRouteChildren = {
  CheckerAcceptTokenRoute: CheckerAcceptTokenRoute,
}

const CheckerRouteWithChildren =
  CheckerRoute._addFileChildren(CheckerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckerRoute: CheckerRouteWithChildren,
  LoginRoute: LoginRoute,
  MyTicketsRoute: MyTicketsRoute,
  SignupRoute: SignupRoute,
  EventsIdRoute: EventsIdRoute,
  HostDashboardRoute: HostDashboardRoute,
  HostOnboardingRoute: HostOnboardingRoute,
  HostEventsNewRoute: HostEventsNewRoute,
  HostEventsIdCheckInRoute: HostEventsIdCheckInRoute,
  HostEventsIdEditRoute: HostEventsIdEditRoute,
  HostEventsIdModerationRoute: HostEventsIdModerationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
